version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: message_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/message_app
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["rails", "server", "-b", "0.0.0.0"]

  sidekiq:
    build: .
    depends_on:
      - redis
      - backend
    command: ["bundle", "exec", "sidekiq"]
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/message_app
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  postgres_data:
